---
version: '3.8'
services:
  myjenkins: 
     image: jenkins/jenkins
     ports:
       - 5050:8080
     container_name: myjenkins   
  qaserver:
      image: tomee
      ports:
        - 6060:8080
      links:
        - myjenkins:jenkins    
      container_name: qaserver
  prodserver:
      image: tomee
      ports: 
        - 7070:8080
      links: 
        - myjenkins:jenkins
      container_name: prodserver

...

        

