---
version: '3.8'
services: 
   mydb: 
     image: mysql
     environment:
       MYSQL_ROOT_PASSWORD: chaitanya
     volumes:
      - mydb:/var/lib/mysql
   mywordpress:
     image: wordpress
     ports:
        - 8888:80
     volumes:
        - wordpress:/var/www/html
volumes:
  mydb:
  wordpress: 


