---
version: '3.8'
services:
  mypostgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: chaianya
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
  myadminar:
    image: adminer
    ports:
      - 9090:8080  
networks:
  default:
    external: 
     name: chaitanya  



...        
